name: 'Aggregate Worker'
description: 'Aggregate files from a worker'
inputs:
  stage:
    type: string
    required: true
  worker:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Set variables
      id: var
      shell: bash
      run: |
        echo "REPO=/home/runner/apt_repo" >> $GITHUB_OUTPUT
        echo "AGG=/home/runner/apt_repo_dependencies" >> $GITHUB_OUTPUT
    - name: Fetch results of ${{ inputs.worker }}
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.var.outputs.REPO }}
        key: apt-repo-${{ inputs.stage }}-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          apt-repo-${{ inputs.stage }}-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}
    - name: Aggregate files
      shell: bash
      run: |
        cat ${{ steps.var.outputs.REPO }}/pkg_build_status.csv >> ${{ steps.var.outputs.AGG }}/pkg_build_status.csv
        cat ${{ steps.var.outputs.REPO }}/sources.repos |
          if [ -f ${{ steps.var.outputs.AGG }}/sources.repos ]; then
            tail -n+2 # skip "repositories:"
          else
            cat
          fi | tee -a ${{ steps.var.outputs.AGG }}/sources.repos
        rm -f ${{ steps.var.outputs.REPO }}/pkg_build_status.csv ${{ steps.var.outputs.REPO }}/sources.repos ${{ steps.var.outputs.REPO }}/local.yaml
        mv ${{ steps.var.outputs.REPO }}/* ${{ steps.var.outputs.AGG }}
