name: build

on:
  workflow_dispatch:
  push:

env:
  AGG: /home/runner/apt_repo_dependencies
  DISTRIBUTION: ubuntu

jobs:
  stage-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Investigate source repositories
        run: |
          sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/sbuild
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y vcstool catkin
          mkdir src
          vcs import --recursive --shallow --input sources.repos src
          for PKG in $(catkin_topological_order --only-names); do
            printf "%s:\n  %s:\n  - %s\n" "$PKG" "${{ env.DISTRIBUTION }}" "ros-one-$(printf '%s' "$PKG" | tr '_' '-')" | tee -a local.yaml
          done
          mkdir -p ${{ env.AGG }}
          mv local.yaml ${{ env.AGG }}/local.yaml
          cp sources.repos ${{ env.AGG }}/sources.repos
      - name: Store meta data
        uses: actions/cache/save@v4
        with:
          path: ${{ env.AGG }}
          key: apt-repo-stage-1-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
  stage0-worker0:
    uses: ./.github/workflows/worker.yaml
    needs: stage-1
    if: success()
    with:
      depends: stage-1
      worker: stage0-worker0
  stage0:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage0-worker0]
    with:
      stage: 0
  stage1-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker0
      depends: stage0
  stage1-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker1
      depends: stage0
  stage1-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker2
      depends: stage0
  stage1-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker3
      depends: stage0
  stage1-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker4
      depends: stage0
  stage1-worker5:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker5
      depends: stage0
  stage1-worker6:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker6
      depends: stage0
  stage1-worker7:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker7
      depends: stage0
  stage1-worker8:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker8
      depends: stage0
  stage1-worker9:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage0
    with:
      worker: stage1-worker9
      depends: stage0
  stage1:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage1-worker0, stage1-worker1, stage1-worker2, stage1-worker3, stage1-worker4, stage1-worker5, stage1-worker6, stage1-worker7, stage1-worker8, stage1-worker9]
    with:
      stage: 1
  stage2-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage1
    with:
      worker: stage2-worker0
      depends: stage1
  stage2-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage1
    with:
      worker: stage2-worker1
      depends: stage1
  stage2-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage1
    with:
      worker: stage2-worker2
      depends: stage1
  stage2-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage1
    with:
      worker: stage2-worker3
      depends: stage1
  stage2-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage1
    with:
      worker: stage2-worker4
      depends: stage1
  stage2:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage2-worker0, stage2-worker1, stage2-worker2, stage2-worker3, stage2-worker4]
    with:
      stage: 2
  stage3-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage2
    with:
      worker: stage3-worker0
      depends: stage2
  stage3-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage2
    with:
      worker: stage3-worker1
      depends: stage2
  stage3-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage2
    with:
      worker: stage3-worker2
      depends: stage2
  stage3-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage2
    with:
      worker: stage3-worker3
      depends: stage2
  stage3-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage2
    with:
      worker: stage3-worker4
      depends: stage2
  stage3:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage3-worker0, stage3-worker1, stage3-worker2, stage3-worker3, stage3-worker4]
    with:
      stage: 3
  stage4-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage3
    with:
      worker: stage4-worker0
      depends: stage3
  stage4-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage3
    with:
      worker: stage4-worker1
      depends: stage3
  stage4-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage3
    with:
      worker: stage4-worker2
      depends: stage3
  stage4-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage3
    with:
      worker: stage4-worker3
      depends: stage3
  stage4-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage3
    with:
      worker: stage4-worker4
      depends: stage3
  stage4:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage4-worker0, stage4-worker1, stage4-worker2, stage4-worker3, stage4-worker4]
    with:
      stage: 4
  stage5-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage4
    with:
      worker: stage5-worker0
      depends: stage4
  stage5-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage4
    with:
      worker: stage5-worker1
      depends: stage4
  stage5-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage4
    with:
      worker: stage5-worker2
      depends: stage4
  stage5-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage4
    with:
      worker: stage5-worker3
      depends: stage4
  stage5-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage4
    with:
      worker: stage5-worker4
      depends: stage4
  stage5:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage5-worker0, stage5-worker1, stage5-worker2, stage5-worker3, stage5-worker4]
    with:
      stage: 5
  stage6-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage5
    with:
      worker: stage6-worker0
      depends: stage5
  stage6-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage5
    with:
      worker: stage6-worker1
      depends: stage5
  stage6-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage5
    with:
      worker: stage6-worker2
      depends: stage5
  stage6-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage5
    with:
      worker: stage6-worker3
      depends: stage5
  stage6-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage5
    with:
      worker: stage6-worker4
      depends: stage5
  stage6:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage6-worker0, stage6-worker1, stage6-worker2, stage6-worker3, stage6-worker4]
    with:
      stage: 6
  stage7-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage6
    with:
      worker: stage7-worker0
      depends: stage6
  stage7-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage6
    with:
      worker: stage7-worker1
      depends: stage6
  stage7-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage6
    with:
      worker: stage7-worker2
      depends: stage6
  stage7-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage6
    with:
      worker: stage7-worker3
      depends: stage6
  stage7-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage6
    with:
      worker: stage7-worker4
      depends: stage6
  stage7:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage7-worker0, stage7-worker1, stage7-worker2, stage7-worker3, stage7-worker4]
    with:
      stage: 7
  stage8-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage7
    with:
      worker: stage8-worker0
      depends: stage7
  stage8-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage7
    with:
      worker: stage8-worker1
      depends: stage7
  stage8-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage7
    with:
      worker: stage8-worker2
      depends: stage7
  stage8-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage7
    with:
      worker: stage8-worker3
      depends: stage7
  stage8-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage7
    with:
      worker: stage8-worker4
      depends: stage7
  stage8:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage8-worker0, stage8-worker1, stage8-worker2, stage8-worker3, stage8-worker4]
    with:
      stage: 8
  stage9-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage8
    with:
      worker: stage9-worker0
      depends: stage8
  stage9-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage8
    with:
      worker: stage9-worker1
      depends: stage8
  stage9-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage8
    with:
      worker: stage9-worker2
      depends: stage8
  stage9-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage8
    with:
      worker: stage9-worker3
      depends: stage8
  stage9-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage8
    with:
      worker: stage9-worker4
      depends: stage8
  stage9:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage9-worker0, stage9-worker1, stage9-worker2, stage9-worker3, stage9-worker4]
    with:
      stage: 9
  stage10-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage9
    with:
      worker: stage10-worker0
      depends: stage9
  stage10-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage9
    with:
      worker: stage10-worker1
      depends: stage9
  stage10-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage9
    with:
      worker: stage10-worker2
      depends: stage9
  stage10-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage9
    with:
      worker: stage10-worker3
      depends: stage9
  stage10-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage9
    with:
      worker: stage10-worker4
      depends: stage9
  stage10:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage10-worker0, stage10-worker1, stage10-worker2, stage10-worker3, stage10-worker4]
    with:
      stage: 10
  stage11-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage10
    with:
      worker: stage11-worker0
      depends: stage10
  stage11-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage10
    with:
      worker: stage11-worker1
      depends: stage10
  stage11-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage10
    with:
      worker: stage11-worker2
      depends: stage10
  stage11-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage10
    with:
      worker: stage11-worker3
      depends: stage10
  stage11-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage10
    with:
      worker: stage11-worker4
      depends: stage10
  stage11:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage11-worker0, stage11-worker1, stage11-worker2, stage11-worker3, stage11-worker4]
    with:
      stage: 11
  stage12-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage11
    with:
      worker: stage12-worker0
      depends: stage11
  stage12-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage11
    with:
      worker: stage12-worker1
      depends: stage11
  stage12-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage11
    with:
      worker: stage12-worker2
      depends: stage11
  stage12-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage11
    with:
      worker: stage12-worker3
      depends: stage11
  stage12-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage11
    with:
      worker: stage12-worker4
      depends: stage11
  stage12:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage12-worker0, stage12-worker1, stage12-worker2, stage12-worker3, stage12-worker4]
    with:
      stage: 12
  stage13-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage12
    with:
      worker: stage13-worker0
      depends: stage12
  stage13-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage12
    with:
      worker: stage13-worker1
      depends: stage12
  stage13-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage12
    with:
      worker: stage13-worker2
      depends: stage12
  stage13-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage12
    with:
      worker: stage13-worker3
      depends: stage12
  stage13-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage12
    with:
      worker: stage13-worker4
      depends: stage12
  stage13:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage13-worker0, stage13-worker1, stage13-worker2, stage13-worker3, stage13-worker4]
    with:
      stage: 13
  stage14-worker0:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage13
    with:
      worker: stage14-worker0
      depends: stage13
  stage14-worker1:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage13
    with:
      worker: stage14-worker1
      depends: stage13
  stage14-worker2:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage13
    with:
      worker: stage14-worker2
      depends: stage13
  stage14-worker3:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage13
    with:
      worker: stage14-worker3
      depends: stage13
  stage14-worker4:
    uses: ./.github/workflows/worker.yaml
    if: success() || failure()
    needs: stage13
    with:
      worker: stage14-worker4
      depends: stage13
  stage14:
    uses: ./.github/workflows/aggregate-debs.yaml
    if: always() && !cancelled()
    needs: [stage14-worker0, stage14-worker1, stage14-worker2, stage14-worker3, stage14-worker4]
    with:
      stage: 14
  deploy:
    needs: stage14
    if: success() || failure() # can get cancelled
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
    steps:
      - name: get apt packages from last job
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.AGG }}
          key: apt-repo-stage14-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            apt-repo-stage14-${{ github.sha }}-${{ github.run_id }}
      - name: move packages to repo
        run: |
          mkdir -p /home/runner/apt_repo
          mv ${{ env.AGG }}/* /home/runner/apt_repo/
      - uses: v4hn/ros-deb-builder-action/deploy@rosotest
        if: always()
        with:
          BRANCH: ${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-unstable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
