name: build

on:
  workflow_dispatch:
  push:
    paths:
      - '**.repos'
      - '**.yaml'

jobs:
  stage0-worker0:
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: envs
      worker: stage0-worker0
  stage0:
    if: success() || failure() # can get cancelled
    needs: [stage0-worker0]
    uses: ./.github/workflows/aggregate-debs.yaml
    with:
      stage: 0
  stage1-worker0:
    if: success() || failure() # can get cancelled
    needs: stage0
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: cmake_modules
      depends: stage0
      worker: stage1-worker0
  stage1-worker1:
    if: success() || failure() # can get cancelled
    needs: stage0
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: genmsg
      depends: stage0
      worker: stage1-worker1
  stage1:
    if: success() || failure() # can get cancelled
    needs: [stage1-worker0, stage1-worker1]
    uses: ./.github/workflows/aggregate-debs.yaml
    with:
      stage: 1
  stage2-worker0:
    if: success() || failure() # can get cancelled
    needs: stage1
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: fused
      depends: stage1
