name: build

on:
  workflow_dispatch:
  push:
    paths:
      - '**.repos'
      - '**.yaml'

jobs:
  envs:
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: envs
  cmake_modules:
    if: success() || failure() # can get cancelled
    needs: [envs]
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: cmake_modules
      depends: envs
  genmsg:
    if: success() || failure() # can get cancelled
    needs: [envs]
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: genmsg
      depends: envs
  fused:
    if: success() || failure() # can get cancelled
    needs: [genmsg, cmake_modules]
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: fused
      depends: genmsg # , cmake_modules # TODO: is this supportable?