on:
  workflow_call:
    inputs:
      repos:
        type: string
      depends:
        type: string
      extra_sbuild_conf:
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
      CCACHE_PATH: /home/runner/.cache/ccache
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use apt packages ${{ inputs.depends }}
        id: depends-cache
        if: ${{ inputs.depends }}
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/apt_repo
          key: apt-repo-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-${{ inputs.depends }}-${{ github.sha }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Use ccache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_PATH }}
          key: ccache-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-${{ inputs.repos }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-${{ inputs.repos }}
      - name: Build packages
        uses: v4hn/ros-deb-builder-action/build@rosotest
        timeout-minutes: 330
        continue-on-error: true
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          SBUILD_CONF: "$verbose = 1; ${{ inputs.extra_sbuild_conf }}"
          ROSDEP_SOURCE: rosdep.yaml
          REPOS_FILE: ${{ inputs.repos }}.repos
          CONTINUE_ON_ERROR: true
      - name: Store ccache
        uses: actions/cache/save@v4
        if: always() # save cache on timeout too
        with:
          path: ${{ env.CCACHE_PATH }}
          key: ccache-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-${{ inputs.repos }}-${{ github.sha }}-${{ github.run_id }}
      - name: Cache apt repo unconditionally
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /home/runner/apt_repo
          key: apt-repo-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-${{ inputs.repos }}-${{ github.sha }}-${{ github.run_id }}
