on:
  workflow_call:
    inputs:
      repos:
        type: string
      depends:
        type: string
      worker:
        type: string
      extra_sbuild_conf:
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
      CCACHE_PATH: /home/runner/.cache/ccache
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use apt packages ${{ inputs.depends }}
        id: fetch-dependencies
        if: ${{ inputs.depends }}
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/apt_repo_dependencies
          key: apt-repo-${{ inputs.depends }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            apt-repo-${{ inputs.depends }}-${{ github.sha }}-${{ github.run_id }}
      - name: Verify cache
        if: ${{ inputs.depends }}
        run: |
          if [ -z "${{ steps.fetch-dependencies.outputs.cache-hit }}" ]; then
            echo "Cache not found"
            exit 1
          fi
      - name: Build packages
        uses: v4hn/ros-deb-builder-action/build@rosotest
        timeout-minutes: 330
        #continue-on-error: true
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          SBUILD_CONF: "$verbose = 1; $extra_packages = ['/home/runner/apt_repo_dependencies']; ${{ inputs.extra_sbuild_conf }}"
          ROSDEP_SOURCE: rosdep.yaml
          REPOS_FILE: ${{ inputs.repos }}.repos
          CONTINUE_ON_ERROR: true
      - name: Store apt repo
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /home/runner/apt_repo
          key: apt-repo-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
